# Generated by Django 3.1.3 on 2020-11-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircompany', models.CharField(max_length=45)),
                ('flight_nuber', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('terminal', models.IntegerField()),
                ('arr_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircompany', models.CharField(max_length=45)),
                ('flight_nuber', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('terminal', models.IntegerField()),
                ('gate', models.IntegerField()),
                ('dep_time', models.DateTimeField()),
            ],
        ),
    ]
