# Generated by Django 3.1.3 on 2020-11-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrival',
            old_name='flight_nuber',
            new_name='flight_number',
        ),
        migrations.RenameField(
            model_name='departure',
            old_name='flight_nuber',
            new_name='flight_number',
        ),
    ]
