# Generated by Django 3.1.3 on 2020-12-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_schedule', '0002_auto_20201128_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='arr_time',
        ),
        migrations.RemoveField(
            model_name='departure',
            name='dep_time',
        ),
        migrations.AddField(
            model_name='arrival',
            name='aircraft',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='arrival',
            name='flight_id',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='arrival',
            name='flight_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='departure',
            name='aircraft',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='departure',
            name='boarding_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='departure',
            name='boarding_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='departure',
            name='desk',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='departure',
            name='flight_id',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='departure',
            name='flight_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='departure',
            name='reg_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='departure',
            name='reg_start',
            field=models.DateTimeField(null=True),
        ),
    ]
