# Generated by Django 3.1.3 on 2020-12-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_schedule', '0003_auto_20201224_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='aircraft',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='flight_id',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='flight_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='departure',
            name='aircraft',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='departure',
            name='flight_id',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='departure',
            name='flight_time',
            field=models.DateTimeField(),
        ),
    ]
